apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: jenkins

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-admin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: jenkins
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: jenkins-admin
