kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-ca-codigofacilito-local
  namespace: jenkins
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"