apiVersion: v1
kind: Pod
metadata:
  name: skaffold
spec:
  containers:
    - name: skaffold
      image: gcr.io/k8s-skaffold/skaffold:v2.10.1
      command: ["bash", "-c"]
      args:
      - openssl s_client -showcerts -servername git.codigofacilito.local -connect git.codigofacilito.local:443  < /dev/null | openssl x509 > /usr/local/share/ca-certificates/rootCA-key.crt;
        update-ca-certificates;
        cat
      tty: true
      imagePullPolicy: Always
      resources:
        requests:
          cpu: "256m"
          memory: "128Mi"
        limits:
          cpu: "512m"
          memory: "256Mi"
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock
